require 'rspec'
require_relative '../strings_arrays/all_unique.rb'
require_relative '../strings_arrays/permutation_finder.rb'
require_relative '../strings_arrays/reverse.rb'
require_relative '../strings_arrays/clean_chars.rb'
require_relative '../strings_arrays/encode_chars.rb'